---
title: "Total Expenditures for Materials analysis"
author: "Michele Claibourn and Clay Ford"
date: "November 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Request from Donna Tolson

I’d like you to run regressions to see where we land among the various peer groups, and if possible, to forecast what the model would predict our expenditures should be, compared to what they are. 

```{r echo=FALSE, message=FALSE}
library(tidyverse)
library(scales)

arl <- readRDS("arl.Rds")
uva <- filter(arl, inam == "VIRGINIA")[1,]
uva_actual <- uva$explm
compare <- function(predicted, actual){
  cat("Predicted:", dollar(predicted), "\nActual:   ", dollar(uva_actual))
  }

comparePlot <- function(model, predicted){
  par(mfrow=c(1,2))
  mod.res <- resid(model)
  x1 <- predicted - uva_actual
  hist(mod.res, breaks=15, xlab="Actual-Predicted Value", main="Histogram of Residuals", col="gray90")
  points(x1, 0, col="orange", pch=19)
  plot(mod.res, ylab="Actual-Predicted Value", main="Plot of Residuals")
  abline(h=0)
  points(x1, col="orange", pch=19)

}

```

## All ARL

```{r }
mod1 <- lm(explm ~ phdawd + fac + totstu, 
           data = arl, 
           subset = subset == "all_arl" & inam != "VIRGINIA")
pred1 <- predict(mod1, newdata = uva)
compare(pred1)

```

```{r echo=FALSE, warning=FALSE}
comparePlot(mod1, pred1)

```


## US Only


```{r }
mod2 <- lm(explm ~ phdawd + fac + totstu, 
           data = arl, 
           subset = subset == "us_only" & inam != "VIRGINIA")
pred2 <- predict(mod2, newdata = uva)
compare(pred2)

```

```{r echo=FALSE, warning=FALSE}
comparePlot(mod2, pred2)

```

## SCHEV UVA

```{r }
mod3 <- lm(explm ~ phdawd	+ phdfld + fac + totstu + totpt +	gradstu + gradpt, 
           data = arl, 
           subset = subset == "schev_uva" & inam != "VIRGINIA")
pred3 <- predict(mod3, newdata = uva)
compare(pred3)

```

```{r echo=FALSE, warning=FALSE}
comparePlot(mod3, pred3)

```

## ARL peers

```{r }
mod4 <- lm(explm ~ phdawd + fac + totstu, 
           data = arl, 
           subset = subset == "arl_peers" & inam != "VIRGINIA")
pred4 <- predict(mod4, newdata = uva)
compare(pred4)

```

```{r echo=FALSE, warning=FALSE}
comparePlot(mod4, pred4)

```


## Scholarly Infrastructure peers


```{r }
mod5 <- lm(explm ~ phdawd + fac + totstu, 
           data = arl, 
           subset = subset == "scholarly_infrastructure_peers" & inam != "VIRGINIA")
pred5 <- predict(mod5, newdata = uva)
compare(pred5)

```

```{r echo=FALSE, warning=FALSE}
comparePlot(mod5, pred5)

```

